name: Deploy to Oracle cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH to Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: 22
          script: |
            cd ~/Smartsplit
            git pull origin main
            npm run build
            pm2 restart smartsplit || sudo pm2 restart smartsplit